"""
Deprecated reports (v1). Use reports_v2.py for history-based analysis.

Legacy v1 reports live under legacy/reports.py and require
data/market_analysis.csv (generated by legacy/main.py).
"""
import sys

if __name__ == "__main__":
    print("Deprecated. Run: python reports_v2.py", file=sys.stderr)
    sys.exit(2)
